back/api/urls.py
from django.urls import path, include
from api.views.v1.jwt import JwtToken, TokenRefresh
from api.views.v1.phones_view import PhonesAPIView, PhonesDetailView
from api.views.v1.project_view import ProjSettingsListCreateView, ProjSettingsDetailView
from api.views.v1.settings import SettingsView, ExtensionsView, DocStatusViewSet

settings_urls = [
    path('database/', SettingsView.as_view(), name='settings'),
    path('extensions/', ExtensionsView.as_view(), name='extensions'),
    path('status/', DocStatusViewSet.as_view(), name='status'),
]

jwt_urls = [
    path('token/', JwtToken.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefresh.as_view(), name='token_refresh'),
]

project_urls = [
    path('projects/', ProjSettingsListCreateView.as_view(), name='projects'),
    path('projects/<uuid:pk>/', ProjSettingsDetailView.as_view(), name='project_detail'),
]

view_urls = [
    path('phones/', PhonesAPIView.as_view(), name='phones'),
    path('phones/<uuid:pk>/', PhonesDetailView.as_view(), name='phones_detail'),
]
generic_patterns = [
    # path('database/', views.DataBaseViewSet.as_view(), name='database'),
    # path('proj_settings/', views.ProjectSettingsView.as_view(), name='proj_settings'),
    # path('proj_control/', views.ProjectStartView.as_view(), name='proj_control'),
    # path('phones/', views.PhonesView.as_view(), name='phones_view'),
    # path('directories/', views.DirectoriesView.as_view(), name='directories'),
]

urlpatterns = [
    path('settings/', include(settings_urls)),
    path('jwt/', include(jwt_urls)),
    path('project/', include(project_urls)),
    path('view/', include(view_urls)),
]

back/get_phone_view/urls.py
from django.contrib import admin
from django.urls import path, include
from .spectacular import urlpatterns as spectacular_url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
]

urlpatterns += spectacular_url

back/index/urls.py
from django.urls import path, re_path
from django.conf.urls.static import static
from . import views

app_name = 'index'

urlpatterns = [
    path('', views.IndexViewApi.as_view(), name='index'),
    path('phones/', views.IndexViewApi.as_view(), name='index'),
    path('training/', views.IndexViewApi.as_view(), name='index'),
    path('settings/', views.IndexViewApi.as_view(), name='index'),
]

back/api/models.py
import uuid
from typing import Tuple

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _

from api.validators import ip_validator
from base.regex import NumberSelection
from services.regular_expression import FindRegex


class DocStatusModel(models.Model):
    status_name = models.CharField(_("documents status name"), max_length=100)

    class Meta:
        db_table = 'doc_status'
        verbose_name = _('doc status')
        verbose_name_plural = _('doc status')


class DocumentsModel(models.Model):
    status = models.ForeignKey(
        DocStatusModel,
        on_delete=models.CASCADE,
        verbose_name=_("doc status"),
    )
    filename = models.CharField(_("filename"), max_length=500)
    filepath = models.CharField(_("filepath"), max_length=1000)
    date = models.DateTimeField(_("document date"), blank=True, null=True)

    @property
    def url(self):
        return f'{settings.MEDIA_URL}/{self.filepath}'

    class Meta:
        db_table = 'documents'
        verbose_name = _('document')
        verbose_name_plural = _('documents')
        indexes = [
            models.Index(fields=['date']),
        ]
        ordering = [
            'date',
        ]


class ParagraphsModel(models.Model):
    doc = models.ForeignKey(
        DocumentsModel,
        on_delete=models.CASCADE,
        verbose_name=_('documents'),
        related_name='paragraphs',
    )
    text = models.TextField(
        verbose_name=_('paragraph text'),
    )

    class Meta:
        db_table = 'paragraphs'
        verbose_name = _('paragraph')
        verbose_name_plural = _('paragraphs')


class TelephonesModel(models.Model):
    paragraph = models.ForeignKey(
        ParagraphsModel,
        on_delete=models.CASCADE,
        verbose_name=_('paragraph'),
        related_name='telephones',
    )
    number = models.CharField(
        _('telephones'),
        max_length=50,
    )
    number_integer = models.BigIntegerField(
        _('integer telephones'),
    )

    @property
    def filepath(self):
        return self.paragraph.doc.filepath

    @property
    def text(self) -> NumberSelection:
        return FindRegex().find_phone(self.paragraph.text, self.number)[1]

    class Meta:
        db_table = 'telephones'
        verbose_name = (_('telephone'),)
        verbose_name_plural = (_('telephones'),)
        indexes = [models.Index(fields=['number_integer']), models.Index(fields=['number'])]


class SurnamesModel(models.Model):
    paragraph = models.ForeignKey(ParagraphsModel, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    patronymic = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)

    class Meta:
        db_table = 'surnames'
        indexes = [
            models.Index(fields=['name']),
            models.Index(fields=['patronymic']),
            models.Index(fields=['surname']),
        ]


class SettingsModel(models.Model):
    db_ip = models.CharField(
        _('database ip'),
        max_length=100,
        validators=[
            ip_validator,
        ],
    )
    db_port = models.IntegerField(
        _('db port'),
    )
    db_path = models.CharField(_('database path'), max_length=300)
    db_login = models.CharField(_('database login'), max_length=100)
    db_password = models.CharField(_('database password'), max_length=100)

    class Meta:
        db_table = 'settings'
        verbose_name = _('settings')
        verbose_name_plural = _('settings')


class DocExtensionModel(models.Model):
    extension = models.CharField(_('extension name'), max_length=30)

    class Meta:
        db_table = 'doc_extensions'
        verbose_name = _('extension')
        verbose_name_plural = _('extensions')


class ProjectsSettings(models.Model):
    id = models.UUIDField(
        _('project id'),
        default=uuid.uuid4,
        primary_key=True,
    )

    class ProjTypeChoices(models.TextChoices):
        SEARCH = "SR", _("Search proj")
        REFRESH = "RF", _("Refresh proj")

    proj_type = models.CharField(
        _('proj type'),
        max_length=100,
        choices=ProjTypeChoices.choices,
        default=ProjTypeChoices.SEARCH,
    )
    options = models.JSONField(
        _('proj options'),
        default=dict,
    )
    is_start = models.BooleanField(
        _('proj is started'),
        default=False,
    )
    created_at = models.DateTimeField(
        _('proj created at'),
        auto_now_add=True,
        blank=True,
        null=True,
    )

    class Meta:
        db_table = 'project_settings'
        verbose_name = _('project setting')
        verbose_name_plural = _('projects settings')

back/index/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _


class UserRequestsList(models.Model):
    class RequestType(models.TextChoices):
        PHONE_REQUEST = "PH", _("phone request")
        PERSON_REQUEST = "PR", _("person request")

    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True)
    filter_params = models.JSONField(
        _('filter params to queryset'),
        default=dict,
    )
    validate_data = models.JSONField(_('valid data request'), default=dict)
    user = models.ForeignKey(
        User, verbose_name=_('users query'), on_delete=models.CASCADE, related_name='requests'
    )
    request_type = models.CharField(max_length=2, choices=RequestType.choices)

    created_at = models.DateTimeField(
        _('request created date'),
        auto_now_add=True,
    )

    class Meta:
        db_table = 'requests'
        verbose_name = _('request')
        verbose_name_plural = _('requests')

back/index/templates/index/def_head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'index/css/media.css' %}">
<!-- Bootstrap CSS -->
<link href="{% static 'index/css/bootstrap.min.css' %}" rel="stylesheet"
      integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<script src="{% static 'index/js/jquery.min.js' %}"></script>
<script src="{% static 'index/js/bootstrap.bundle.min.js' %}"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>
<script src="{% static 'index/js/script_new.js' %}"></script>
<script src="{% static 'index/js/air-datepicker.js' %}"></script>
<link rel="stylesheet" href="{% static 'index/bootstrap-icons.css' %}">
<link rel="stylesheet" href="{% static 'index/style.css' %}?3">
<link rel="stylesheet" href="{% static 'index/css/blink_text.css' %}">
<link rel="stylesheet" href="{% static 'index/css/preloader.css' %}">
<link href="{% static 'index/css/air-datepicker.css' %}" rel="stylesheet" type="text/css">

back/index/templates/index/index.html
<!DOCTYPE html><html><head><title>get_phone_view</title><meta charset=utf-8><meta name=description content=get_phone_view><meta name=format-detection content="telephone=no"><meta name=msapplication-tap-highlight content=no><meta name=viewport content="user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1,width=device-width"><link rel=icon type=image/png sizes=128x128 href="/icons/favicon-128x128.png"><link rel=icon type=image/png sizes=96x96 href="/icons/favicon-96x96.png"><link rel=icon type=image/png sizes=32x32 href="/icons/favicon-32x32.png"><link rel=icon type=image/png sizes=16x16 href="/icons/favicon-16x16.png"><link rel=icon type=image/ico href="/favicon.ico">  <script type="module" crossorigin src="/assets/index.8f2b4bb4.js"></script>
  <link rel="stylesheet" href="/assets/index.b9168b59.css">
</head><body><div id=q-app></div></body></html>

back/index/templates/index/index_.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    {% include 'index/def_head.html' %}
    <link rel="stylesheet" href="{% static 'index/css/index.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/popup_form.css' %}">
    <script src="{% static 'index/js/index.js' %}"></script>
    <script src="{% static 'index/js/popup_form.js' %}"></script>
    <title>ИЗВЛЕЧЕНИЕ ТЕЛЕФОННЫХ НОМЕРОВ</title>
</head>
<header>
    {% include 'index/navbar.html' %}
</header>
<body>

<div id="block1" class="div-block container-fluid">
    <div class="row row-title">
        <div class="col">
            <h7>Извлечение именнованных сущностей</h7>
        </div>
    </div>
    <div class="row proj-div" id="row-file-path">
        <form class="settings-form">
            {% csrf_token %}
            <input type="text" name="event" value="set_entity_proj" class="hidden">
            <div class="col-12">
                <div class="col-12 col-md-3 mb-3">
                    <label for="data-folder" class="form-label">Папка для обработки</label>
                    <input id="data-folder" name="data_folder" type="text" class="form-control"
                           placeholder="{{ entity_settings.proj_settings.data_folder }}"
                           required>
                    <div class="invalid-feedback"></div>
                </div>
                <div class="col-12 col-md-3 mb-3">
                    <label for="log-name" class="form-label">Имя лог файла</label>
                    <input id="log-name" type="text" name="log_name" class="form-control"
                           placeholder="{{ entity_settings.proj_settings.log_name }}"
                           required>
                    <div class="invalid-feedback"></div>
                </div>
                <div class="col-12 col-md-3 mb-3">
                    <label for="log-name" class="form-label">Максимум времени</label>
                    <input id="log-time" type="text" name="time_processing" class="form-control"
                           placeholder="{{ entity_settings.proj_settings.time_processing }}"
                           required>
                    <div class="invalid-feedback"></div>
                </div>
                <div class="col-12 col-md-3 mb-3">
                    <label for="doc-date-input" class="form-label">Дата документов</label>
                    <div class="input-group">
                        <div class="input-group-text">
                            <input class="auto-date-check form-check-input mt-0" type="checkbox" name="auto_date"
                                   value="True"
                                   aria-label="Checkbox for following date input"
                                    {% if entity_settings.proj_settings.auto_date %} checked {% endif %}>
                        </div>
                        <input id="doc-date-input" type='text' name="doc_date" class='datepicker-here form-control'
                               data-language='en' {% if entity_settings.proj_settings.auto_date %} disabled{% endif %}/>
                        <div class="invalid-feedback"></div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div style="position: relative" class="col-12 col-md-3 mb-3">
                    <label for="doc-extensions" class="form-label">Расширения документов</label>
                    <input id="doc-extensions" type="text" class="form-control" readonly>
                    <div id="popup-div" class="popup-div data-map">
                        <ul>
                            {% for file_extension in file_extensions %}
                                <li>
                                    <div class=" form-switch m-1">
                                        <input class="form-check-input" type="checkbox"
                                               name="{{ file_extension.extension }}" value="True"
                                                {% for key in entity_settings.proj_settings.data_array %}
                                                    {% if key == file_extension.extension %}
                                               checked
                                                    {% endif %}
                                                {% endfor %}>
                                        <label class="form-check-label"
                                               for="flexSwitchCheckDefault">{{ file_extension.extension }}</label>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="form-check me-2">
                    <input class="form-check-input" type="checkbox" name="check_processed_file" value="True"
                           id="flexCheckDefault" {% if entity_settings.proj_settings.check_processed_file %}
                           checked{% endif %}>
                    <label class="form-check-label" for="flexCheckDefault">
                        Check processed file
                    </label>
                </div>
                <div class="form-check me-2">
                    <input class="form-check-input" type="checkbox" name="sync_proj" value="True"
                           id="flexCheckDefault" {% if entity_settings.proj_settings.sync_proj %}
                           checked{% endif %}>
                    <label class="form-check-label" for="flexCheckDefault">
                        Only Tag
                    </label>
                </div>
            </div>
        </form>
        <div class="col-12">
            <div class="settings-block">
                <button class="verification-btn btn btn-success" type="button" {% if entity_settings.is_run %}
                        disabled {% endif %} >Проверка
                </button>
                <div id="connect2base" class="invalid-feedback">
                    No Files
                </div>
            </div>
            <div class="play-block">
                <form>
                    <input type="text" name="event" value="run_entity_proj" class="hidden">
                    <button type="button" class="play-btn btn btn-outline-success m-2"
                            disabled><i class="bi bi-collection-play"></i>
                    </button>
                    <button type="button" data-proj="entity_proj" class="stop-btn btn btn-outline-danger m-2"
                            {% if not entity_settings.is_run %}
                            disabled {% endif %}><i class="bi bi-stop"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<div id="block2" class="div-block container-fluid">
    <div class="row row-title">
        <div class="col">
            <h7>Переобучение выборки</h7>
        </div>
    </div>
    <div class="row proj-div" id="row-file-path">
        <form class="settings-form">
            {% csrf_token %}
            <input type="text" name="event" value="set_retraining_proj" class="hidden">
            <div class="col-12">
                <div style="position: relative" class="col-12 col-md-3 mb-3">
                    <label for="doc-status" class="form-label">Статус документов</label>
                    <input id="doc-status" type="text" class="form-control" readonly>
                    <div id="popup-div-status" class="popup-div data-map">
                        <ul>
                            {% for status in doc_status %}
                                <li>
                                    <div class=" form-switch m-1">
                                        <input class="form-check-input" type="checkbox"
                                               name="{{ status.status }}" value="True"
                                                {% for key in retraining_settings.proj_settings.data_array %}
                                                    {% if key == status.status %}
                                               checked
                                                    {% endif %}
                                                {% endfor %}>
                                        <label class="form-check-label"
                                               for="flexSwitchCheckDefault">{{ status.status }}</label>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="col-12 col-md-3">
                    <label for="log-name" class="form-label">Имя лог файла</label>
                    <input id="log-name" type="text" name="log_name" class="form-control"
                           placeholder="{{ retraining_settings.log_file }}"
                           required>
                    <div class="invalid-feedback"></div>
                </div>
                <div class="col-12 col-md-3">
                    <label for="log-name" class="form-label">Максимум времени</label>
                    <input id="log-time" type="text" name="time_processing" class="form-control"
                           placeholder="{{ retraining_settings.proj_settings.time_processing }}"
                           required>
                    <div class="invalid-feedback"></div>
                </div>
                <div class="col-12 col-md-3">
                    <label for="doc-date-retrain" class="form-label">Дата документов</label>
                    <div class="input-group">
                        <div class="input-group-text">
                            <input class="auto-date-check form-check-input mt-0" type="checkbox" name="auto_date"
                                   value="True"
                                   aria-label="Checkbox for following date input"
                                    {% if retraining_settings.proj_settings.auto_date %} checked {% endif %}>
                        </div>
                        <input id="doc-date-retrain" type='text' name="doc_date" class='datepicker-here form-control'
                               data-language='en' {% if retraining_settings.proj_settings.auto_date %}
                               disabled {% endif %}/>
                        <div class="invalid-feedback"></div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="col-12 col-md-3">
                    <label for="doc_id" class="form-label">ID Документа</label>
                    <input id="doc_id" name="doc_id" type="number" class="form-control"
                           placeholder="{{ retraining_settings.proj_settings.doc_id }}" required>
                </div>
            </div>
            <div class="col-12">
                <div class="form-check me-2">
                    <input class="form-check-input" type="checkbox" name="delete_non_existent" value="True"
                           id="flexCheckDefault" {% if retraining_settings.proj_settings.delete_non_existent %}
                           checked{% endif %} >
                    <label class="form-check-label" for="flexCheckDefault">
                        Delete non existent
                    </label>
                </div>
            </div>
        </form>
        <div class="col-12">
            <div class="settings-block">
                <button class="verification-btn btn btn-success" type="button" {% if retraining_settings.is_run %}
                        disabled {% endif %} >Проверка
                </button>
                <div id="connect2base" class="invalid-feedback">
                    No Files
                </div>
            </div>
            <div class="play-block">
                <form>
                    <input type="text" name="event" value="run_retraining_proj" class="hidden">
                    <button type="button" class="play-btn btn btn-outline-success m-2"
                            disabled><i class="bi bi-collection-play"></i>
                    </button>
                    <button type="button" data-proj="retrain_proj" class="stop-btn btn btn-outline-danger m-2"
                            {% if not retraining_settings.is_run %}
                            disabled {% endif %}><i class="bi bi-stop"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
<div id="error-block" class="hidden container-fluid">
    <div class="row">
        <div class="col">
            <h5 id="error_txt"></h5>
        </div>
    </div>
</div>
<div id="block4" class="div-block container-fluid">
    <div class="row row-title">
        <div class="col">
            <h7>Логи</h7>
        </div>
    </div>
</div>
<script>
    $(document).ready(() => {
        let datepicker1 = new AirDatepicker('#doc-date-input', {
            selectedDates: [new Date()]
        });
        let datepicker2 = new AirDatepicker('#doc-date-retrain', {
            selectedDates: [new Date()]
        });
        let datepicker3 = new AirDatepicker('#doc-date-sync',{
            selectedDates: [new Date()]
        });
    });
</script>
</body>
</html>

back/index/templates/index/logfiles.html
{% for line in text %}
    <div>{{ line }}</div>
{% endfor %}

back/index/templates/index/modal.html
<!-- Modal -->
<div class="modal fade" id="modalWindow" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-success hidden">Commit</button>
            </div>
        </div>
    </div>
</div>

back/index/templates/index/navbar.html
<nav class="navbar navbar-expand-lg navbar-expand-md navbar-expand-sm navbar-dark">
    <div class="container-fluid">
        <span class="navbar-brand"><span class="fast-flicker">O</span>SA</span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <i class="bi bi-box-arrow-in-up-left"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'search_numbers:index' %}">Просмотр номеров</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'search_fio:index' %}">Просмотр ФИО</a>
                </li>
                {% if request.user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'index:index' %}">Обучение</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'OSA_settings:index' %}">Настройки</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a id="logout-href" class="nav-link" data-url={% url 'custom_auth:login' %} href="#">Выход</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<script>
    $(document).ready(function () {
            $(document).on('click', '#logout-href', function (event) {
                event.stopPropagation();
                event.preventDefault();
                let data_url = $(this).attr("data-url");
                let data = {'event': 'logout'}
                send_json_ajax(data, data_url, reload_window, console_log);
            });
        }
    );
</script>

back/index/templates/index/pagination.html
<div class="row">
    <div class="col-md-12 text-center">
        <nav class="page-nav" aria-label="Page navigation">
            <ul class="pagination">
                {% for item in navigation.array %}
                    {% if navigation.page_id == item %}
                        <li class="page-item disabled"><a class="page-link" href="{% url navigation.url %}?page_id={{ item }}">{{ item }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="{% url navigation.url %}?page_id={{ item }}">{{ item }}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </nav>
    </div>
</div>